export const namadwaarData = {
  india: [
    { id: 'kalyanasrinivasa', name: 'Sri Kalyanasrinivasa Perumal Koil', address: 'Maharanyam Village, Malaipattu, Tamil Nadu 601301', coords: [80.0, 12.9] },
    { id: 'chaitanya', name: 'Sri Chaitanya Kuteeram', address: 'Rama Nama Sannidhi Street, Aduthurai, Tamil Nadu 612101', coords: [79.4, 11.0] },
    { id: 'ambasamudram', name: 'Ambasamudram', address: 'No: 11 - 12, Ammaiyappa Sannadhi Street, Nellai Dist 627401', coords: [77.4, 8.7] },
    { id: 'annanagar', name: 'Anna Nagar', address: 'No,1803/19, 2nd St, Vasantham Colony, Anna Nagar, Chennai 600040', coords: [80.2, 13.0] },
    { id: 'arakkonam', name: 'Arakkonam', address: '36, Balasundaram St, Gandhi Nagar, Arakkonam 631001', coords: [79.6, 13.0] },
    { id: 'aruppukkottai', name: 'Aruppukkottai', address: 'Mela Theru, Shanmuganatha Puram, Mani Nagaram, Aruppukkottai 626101', coords: [78.1, 9.5] },
    { id: 'bathalagundu', name: 'Bathalagundu', address: 'Uday Nivas, 9/6/24, Ottrai Street, Agraharam, Batlagundu 624202', coords: [77.7, 10.1] },
    { id: 'bengaluru', name: 'Bengaluru', address: '4, 33rd Cross Rd, 4th T Block East, Pattabhirama Nagar, Jayanagar 560041', coords: [77.5, 12.9] },
    { id: 'chidambaram', name: 'Chidambaram', address: '26, Ilamaiyakkinar Koil St, Chidambaram 608001', coords: [79.6, 11.3] },
    { id: 'chitradurga', name: 'Chitradurga', address: 'Rayapura Village, Molakalmuru Taluk, Chitradurga 577535', coords: [76.4, 14.2] },
    { id: 'chromepet', name: 'Chromepet', address: '29, Krishnamachari Street, Radha Nagar, Chromepet, Chennai 600044', coords: [80.1, 12.9] },
    { id: 'cuddalore', name: 'Cuddalore', address: '8, Barathidasan Street, Allpettai, Manjakuppam, Cuddalore 607001', coords: [79.7, 11.7] },
    { id: 'dommasandra', name: 'Dommasandra', address: 'Chandapura Road, Vinayak Nagar, 13th Ward, Dommsandra', coords: [77.7, 12.8] },
    { id: 'ernakulam', name: 'Ernakulam', address: 'Omkar, Adampally Kavu Road, NF Gate, Thrippunithura, Kochi 682301', coords: [76.3, 9.9] },
    { id: 'gobichettipalayam', name: 'Gobichettipalayam', address: '66, Esvaran Kovil Street, Erode District 638452', coords: [77.4, 11.4] },
    { id: 'gudiyatham', name: 'Gudiyatham', address: 'Pillayar Koil St, Pandiyan Nagar, Tharanampet, Gudiyatham 635803', coords: [78.8, 12.9] },
    { id: 'hosakote', name: 'Hosakote', address: 'Gundur Village, Hosakote Taluk, Bangalore Rural District', coords: [77.8, 13.0] },
    { id: 'hubbali', name: 'Hubbali', address: 'No:182, Gokul Road, Jayaprakash Nagar, Hubballi 580030', coords: [75.1, 15.3] },
    { id: 'kalatipet', name: 'Kalatipet', address: '5/103, Kakkanji St, Kalattipet, Kundrathur, Chennai 600069', coords: [80.0, 12.9] },
    { id: 'kariyapatti', name: 'Kariyapatti', address: 'Pillaiyar Koil Street, Azhagar Sami Nagar, Kariapatti 626106', coords: [78.1, 9.6] },
    { id: 'kolar', name: 'Kolar', address: 'Samapangere Village, Malur Taluk, Kolar District', coords: [78.1, 13.1] },
    { id: 'kovilpatti', name: 'Kovilpatti', address: 'Kasiraja Bhavanam, Vadakku Pudhu Kiramam, 26, J.A, 3rd St, MGR Nagar 628501', coords: [77.8, 9.1] },
    { id: 'kovur', name: 'Kovur', address: '5/44, S Mada St, Kovur, Chennai 600128', coords: [80.1, 13.0] },
    { id: 'madurai', name: 'Madurai', address: 'Plot No 121, Door No 214, Elango Street, EB Colony, Iyer Bungalow 625014', coords: [78.1, 9.9] },
    { id: 'malaipattu', name: 'Malaipattu', address: 'Renukambal Koil Street, Malaipattu Panchayat, Padappai 601301', coords: [80.0, 12.8] },
    { id: 'mannargudi', name: 'Mannargudi', address: '26/31, Haridra Nadhi S, Mannargudi 614001', coords: [79.4, 10.6] },
    { id: 'mayiladuthurai', name: 'Mayiladuthurai', address: 'C 11, near Railady, Cauvery Nagar, Koranad 609001', coords: [79.6, 11.1] },
    { id: 'periyakulam', name: 'Periyakulam', address: '92/112, S Agraharam, Thenkarai 625601', coords: [77.5, 10.1] },
    { id: 'salem', name: 'Salem', address: '81 Gandhi Road, Opp TVN Kalyana Mandapam 636007', coords: [78.1, 11.6] },
    { id: 'sattur', name: 'Sattur', address: '11, Nadar Keela Theru, Sattur 626203', coords: [77.9, 9.3] },
    { id: 'senganoor1', name: 'Senganoor', address: 'Mahathma Sri Sri Krishnapremi Swamigal theru, Senganoor', coords: [79.4, 11.1] },
    { id: 'senganoor2', name: 'Senganoor Bhajanai Madam', address: 'sri sri anna bhajanai madam, Arch theru, Senganur main road 612504', coords: [79.4, 11.1] },
    { id: 'sivakasi', name: 'Sivakasi', address: 'S, Viswanattham Rd, 60,Patti St, Theru, Sivakasi 626123', coords: [77.7, 9.4] },
    { id: 'sivathiyapuram', name: 'Sivathiyapuram', address: 'Vinayagar Temple Street -East, Sivathiyapuram, Tuticorin 628251', coords: [78.0, 8.7] },
    { id: 'sriperumpudur', name: 'Sriperumpudur', address: 'Thirumangai Azhwar Street, Opp road to Jaya Hospital, Sriperumbudur', coords: [79.9, 12.9] },
    { id: 'srivilliputhur', name: 'Srivilliputhur', address: '6C,Dhrowpathy, Amman Kovil Rd, Srivilliputhur 626125', coords: [77.6, 9.5] },
    { id: 'thanjavur', name: 'Thanjavur', address: 'Plot No :23A, Natarajapuram North, Statebank Colony, Medical College Rd', coords: [79.1, 10.7] },
    { id: 'tharapuram', name: 'Tharapuram', address: '141/4,Kulathupunjai Theru, Rsp Nagar, Tharapuram T.k, Thiruppur 638656', coords: [77.5, 10.7] },
    { id: 'tirunelveli', name: 'Tirunelveli', address: '146, 17th cross street, Balabakyam Nagar South, Tirunelveli Junction 627001', coords: [77.7, 8.7] },
    { id: 'tiruttani', name: 'Tiruttani', address: '30, Old Bazar street, (Near Pilliyar Kovil) 631209', coords: [79.6, 13.1] },
    { id: 'trichy', name: 'Trichy', address: '15, Shastri Rd, Near Saradambal Koil, AVR complex, Tennur 620017', coords: [78.6, 10.8] },
    { id: 'tuticorin', name: 'Tuticorin', address: 'No :218,Vadakku Radha Veedhi, Tuticorin Melur 628002', coords: [78.1, 8.7] },
    { id: 'udumalaipet', name: 'Udumalaipet', address: 'C 70/2,Gandhi Nagar, Udumalaipet 642126', coords: [77.2, 10.5] },
    { id: 'valliyur', name: 'Valliyur', address: '129C, Perumal kovil, N Car St, Valliyur 627117', coords: [77.6, 8.3] },
    { id: 'virudhunagar', name: 'Virudhunagar', address: 'Railway Feeder Road Lane opposite to Ramar Koil, Virudhunagar 626001', coords: [77.9, 9.5] },
  ],
  international: [
    { id: 'atlanta', name: 'Atlanta (USA)', address: '239 Atlanta Road, Cumming, GA 30040', coords: [-84.1, 34.2] },
    { id: 'dallas', name: 'Dallas (USA)', address: '1881 Apollo Road, Garland, TX', coords: [-96.6, 32.9] },
    { id: 'edmonton', name: 'Edmonton (Canada)', address: '24337, Township Rd 512, Edmonton, AB T6W 1A6', coords: [-113.4, 53.5] },
    { id: 'fiji', name: 'Fiji', address: '44, Oakes Road, Winston Hills, New South Wales (wait, this address is Sydney?)', coords: [178.4, -18.1] },
    { id: 'houston', name: 'Houston (USA)', address: '3642 Bailey Avenue, Manvel, TX 77578', coords: [-95.3, 29.4] },
    { id: 'malaysia', name: 'Malaysia', address: '59 A Jalan USJ 21/11, UEP, Subang Jaya, 47600 Selangor, Malaysia', coords: [101.5, 3.0] },
    { id: 'melbourne', name: 'Melbourne (Australia)', address: 'Unit 12 No 7, Samantha Court, Knoxfield, Melbourne, Victoria', coords: [145.2, -37.8] },
    { id: 'nz', name: 'New Zealand', address: '21A Huntingtree Avenue, Sandringham, Auckland 1041', coords: [174.7, -36.8] },
    { id: 'seattle', name: 'Seattle (USA)', address: '33404 SE Redmond Fall City Rd, #120, Fall City, Washington 9802', coords: [-121.8, 47.5] },
    { id: 'singapore', name: 'Singapore', address: '448 Serangoon road, Level #02 - 01, Singapore 218138', coords: [103.8, 1.3] },
    { id: 'sydney', name: 'Sydney (Australia)', address: '44, Oakes Road, Winston Hills, New South Wales', coords: [150.9, -33.7] },
    { id: 'virginia', name: 'Virginia (USA)', address: '22495 Landora Bridge Rd, Ruther Glen, Virginia 22546', coords: [-77.4, 37.9] },
  ]
};
